services:
  - type: web
    name: websocket-serveur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn relay_server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
